### ISSUE TITLE
Fill remaining placeholder links

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/ICESat-2-Hackweek-2023#36]
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/ea82c170240899c53017e1e15070f18f76c32104/book/_config.yml#L21-L24

**Comment by aaarendt** [comment]
Completed by https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/pull/55.
