### ISSUE TITLE
Add common data formats to .gitignore

### ISSUE THREAD

**Issue by scottyhq** [ICESAT-2HackWeek/ICESat-2-Hackweek-2023#57]
Many tutorials notebooks download data to their subfolder. In addition to encouraging the use of `/tmp` for data downloads (https://docs.2i2c.org/data/filesystem/#the-tmp-directory). 

I think adding common large binary formats (*.tif, *.h5, *.nc) to .gitignore will help steer people away from committing large files to the repository. cc @jomey @YoungHyunKoo

**Comment by jomey** [comment]
Think this should also be done with the template to prevent these cases in the future.
